baseurl: https://lowkeng.netlify.app/
title: LowKeng BLOG
theme: hugo-theme-cleanwhite
languageCode: en-us
disqusShortname: cnluokun
googleAnalytics: ''
preserveTaxonomyNames: yes
paginate: 5
hasCJKLanguage: yes
outputs:
  home:
    - HTML
    - RSS
    - Algolia
params:
  SEOTitle: Self-disciplined,Self-Motivated
  about_me: yes
  addtional_menus:
    - href: /top/books/
      title: BOOKS
    - href: /top/archive/
      title: ARCHIVE
    - href: /top/about/
      title: ABOUT
  algolia:
    params:
      - categories
      - tags
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
  algolia_apiKey: ''
  algolia_appId: ''
  algolia_indexName: ''
  algolia_search: yes
  ba_track_id: ''
  bookmark_link:
    - href: https://pxhere.com
      title: Pxhere
    - href: https://unsplash.com
      title: unsplash
  bookmarks: no
  description: 罗坤，走过一些弯路的硕士生,  保持乐观，保持热爱 | 这里是 罗坤 的博客，如果命运是世界上最烂的编剧，你就要争取做自己人生最好的演员。
  disqus_proxy: ''
  disqus_site: ''
  featured_condition_size: 1
  featured_tags: yes
  friend_link:
    - title: 友链1 
      href : https://www.zhaohuabing.com/
  friends: yes
  header_image: img/bookpen.jpg
  image_404: img/404-bg.jpg
  keyword: 个人网站，写技术帖，记录学习
  leancloud_app_id: ''
  leancloud_app_key: ''
  omit_categories: yes
  page_view_conter: yes
  reward: yes
  sidebar_about_description: Master Student of CASIA,Life-long Learner and Good-manner Keeper.
  sidebar_avatar: img/robotavatar.png
  slogan: 苟有恒，何必三更眠五更起;最无益，莫过一日曝十日寒
  social:
    email: lksteven2013@163.com
    github: https://github.com/lowkeng 
    #bilibili: https://space.bilibili.com/8877404
    zhihu: https://www.zhihu.com/people/lowkeng
    #linkedin: https://www.linkedin.com/in/yourlinkedinid
    rss: yes
    #stackoverflow: https://stackoverflow.com/users/yourstackoverflowid
    wechat: img/wechatQR.jpg
  title_404: 你来到了没有知识的荒原 :(
  twikoo_env_id: ''
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: yes
    mediaType: application/json
    notAlternative: yes
markup:
  highlight:
    style: dracula
  tableOfContents:
    endLevel: 2
    startLevel: 1
